---
# Tasks for networking.

- name: Apply Networking Configuration
  template:
    src: "{{ item.0 }}"
    dest: "{{ item.1 }}"
    owner: root
    group: root
    mode: 0644
  with_together:
    - "{{ templates }}"
    - "{{ destinations }}"
  notify:
    - Restart Networking

- name: Change Hostname
  hostname: name={{ hostname }}

- meta: flush_handlers

# - name: Update /etc/hosts
#   replace: dest="/etc/hosts" regexp="raspberrypi" replace="{{ hostname }}"
#   notify:
#     - Restart Networking
