---
# Common ansible role for Raspberry Pi cluster.

- name: Expand Root FS
  shell: sudo raspi-config --expand-rootfs
  run_once: yes

- name: Install Core Packages
  apt: name={{ item }} state=present
  with_items:
    - gcc
    - make
    - git
    - python2.7
    - python3.4
