---
# Common ansible role for Raspberry Pi cluster.

- name: Clean up Aptitude
  apt: autoremove="yes" update_cache="yes"

- name: Install Core Packages
  apt: name={{ item }} state=installed
  with_items:
    - gcc
    - make
    - git
    - python2.7
    - python3.4
