---
# Tasks for installing and configuring salt.

- name: Add Raspbian Stretch Repo
  apt_repository: |
    repo="deb http://archive.raspbian.org/raspbian/ stretch main"
    state=present

- name: Ensure apt.conf.d/10apt Exists
  file: path="/etc/apt/apt.conf.d/10apt" state=touch

- name: Make Jessie a Default Release
  lineinfile: |
    dest="/etc/apt/apt.conf.d/10apt"
    regexp='^'
    line="APT::Default-Release {{ '\"' }}jessie{{ '\"' }};"

- name: Update Apt Cache
  apt: update_cache="yes"

- name: Install Dependencies
  apt: name={{ item }} state=installed
  with_items:
    - python-zmq
    - python-tornado/stretch
    - salt-common/stretch

- name: Install Salt Minion
  apt: name={{ item }} state=installed
  with_items:
    - salt-minion/stretch

- name: Install Salt Master
  apt: name={{ item }} state=installed
  with_items:
    - salt-master/stretch
  when: type == "master"

- name: Configure Salt With Static IP
  lineinfile: |
    dest="/etc/salt/master"
    regexp='^#?interface:'
    line="interface: {{ ip_address }}"
    state=present
  when: type == "master"

- name: Get Master Fingerprint
  delegate_to: "rpiomega-master.local"
  command: salt-key -F master | grep -oP "(?<=master\.pub\:\s\s).*$"
  always_run: True
  register: master_fingerprint

- name: Configure Salt With Master
  lineinfile: |
    dest="/etc/salt/minion"
    regexp='^#?master:'
    line="master: rpiomega-master"
    state=present

- name: Add Master Fingerprint to Minion
  lineinfile: |
    dest="/etc/salt/minion"
    regexp='^#?master_finger:'
    line="master_finger: '{{ master_fingerprint }}'"
  notify:
    - Restart Server
    - Wait For Server to Restart

- name: Accept Keys On Salt Master
  delegate_to: "rpiomega-master.local"
  command: salt-key -A
