---
# Tasks for installing and configuring salt.

- name: Add Salt Repo
  apt_repository: |
    repo="{{ salt_repository }}"
    state=present

- name: Add Salt Repo To /etc/apt/sources.list
  lineinfile: |
    dest="/etc/apt/sources.list"
    regexp='^'
    line="{{ salt_repository }}"
    state=present

- name: Make Jessie a Default Release
  lineinfile: |
    dest="/etc/apt/apt.conf.d/10apt"
    regexp='^'
    line="APT::Default-Release {{ '\"' }}jessie{{ '\"' }};"
    state=present
    create=yes

- name: Update Apt Cache
  apt: update_cache="yes"

- name: Install Dependencies
  apt: name="{{ item }}" state=present default_release={{ salt_default_release }}
  with_items:
    - python-zmq
    - python-tornado
    - salt-common

- name: Install Salt Minion
  apt: name={{ item }} state=latest default_release={{ salt_default_release }}
  with_items:
    - salt-minion

- name: Install Salt Master
  apt: name={{ item }} state=latest default_release={{ salt_default_release }}
  with_items:
    - salt-master
  when: type == "master"

- name: Configure Salt With Static IP
  lineinfile: |
    dest="/etc/salt/master"
    regexp='^#?interface:'
    line="interface: {{ ip_address }}"
    state=present
  when: type == "master"

- name: Get Master Fingerprint
  delegate_to: "rpiomega-master.local"
  shell: salt-key -F master | grep -oP "(?<=master\.pub\:\s\s).*$"
  always_run: True
  register: master_fingerprint

- name: Configure Salt With Master
  lineinfile: |
    dest="/etc/salt/minion"
    regexp='^#?master:'
    line="master: rpiomega-master.local"
    state=present

- name: Add Master Fingerprint to Minion
  lineinfile: |
    dest="/etc/salt/minion"
    regexp='^#?master_finger:'
    line="master_finger: '{{ master_fingerprint['stdout'] }}'"
  notify:
    - Restart Server
    - Wait For Server to Restart

- name: Accept Keys On Salt Master
  delegate_to: "rpiomega-master.local"
  become: yes
  shell: salt-key -a {{ ansible_hostname }} -y
  always_run: yes
  ignore_errors: yes

- name: Ensure Salt Minion Service is Started
  service: name=salt-minion state=started

- name: Clone Salt Provisioner Repo
  git:
    repo: "git://github.com/ajthor/rpiomega-salt-provisioner.git"
    dest: "{{ salt_base_dir }}"
    clone: yes
    recursive: yes
  when: type == "master"
